[downloads]
location = "Downloads" # Location to where the downloads will go

[database]
enabled = true # Disable / Enable the database functionality
location = "data/data.db" # Location where the database will be generated

[duplication]
images = true # To check for duplicate images
videos = true # To check for duplicate videos -- intensive
threshold = 0.9 # Threshold to mark files as duplicate: 0.1 = 10% similarity
samples = 3 # Amount of samples to get when checking video duplicates
ffmpeg_path = "C:\\ffmpeg\\bin\\ffmpeg.exe" # Path to FFMPEG for video checking (cuda compatible version best)
ffprobe_path = "C:\\ffmpeg\\bin\\ffprobe.exe" # For probing video files to get frame counts

[network]
timeout = 10 # Time in seconds before a request times out
chunk_size = 1048576 # Chunk size in bytes to download at
cookies = ".cookies" # Folder where cookies.txt files are located

[network.headers]
User-Agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/150.0.0.0 Safari/537.36"
Accept = "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8"
Accept-Encoding = "gzip, deflate, zstd"
Connection = "keep-alive"