# Download settings.
downloads:
  output: Downloads
  
  # Remoe duplicate files after downloading thread.
  remove_duplicates: True

  # Number of bytes to read/write at a time when downloading.
  # 1048576 = 1 MiB
  chunk_size: 1048576

# Network and thread settings.
network:
  # HTTP request timeout in seconds.
  timeout: 30

  # User agent to use in HTTP requests.
  user_agent: {}

  # Number of concurrent download workers.
  workers: 10

# Filtering options
filters:
  # List of domains to ignore.
  # Leave empty to allow all domains.
  excluded_domains: []

  # Example:
  # excluded_domains:
  #   - bunkr
  #   - goonbox